name: eslint-static-analysis 
on:
    push:
        branches:
            - 'dev'
            - 'master'
    pull_request:
        branches:
            - 'main'
            - 'master'

jobs:
  lint-ubuntu-20:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install deps and lint
        run: |
          npm install .
          npx next lint 